# Workflow의 이름
# Workflow : 하나의 yml 파일을 하나의 Workflow라고 부른다.
name: Github Actions 실행시켜보기

# Event : 실행되는 시점을 설정
# main이라는 브랜치에 push 될 때 아래 Workflow를 실행
on:
  push:
    branches:
      - main

# 하나의 Workflow는 반드시 1개 이상의 Job으로 구성.
# 여러 Job은 기본적으로 병렬적 수행.
jobs:

  # Job을 식별하기 위한 Id
  My-Deploy-Job:
    # 실행시킬 서버 종류 선택 -> ubuntu 환경의 가장 최신버전(latest)
    runs-on: ubuntu-latest

    # step: 작업을 수행하는 가장 작은 단위
    # 하나의 Job은 여러 Step들로 구성되어 있음.
    steps:
      - name: Hello World 찍기
        run: echo "Hello World"

      - name: 여러 명령어 문장 작성하기스
        run: |
          echo "Good"
          echo "Dalbong"

      - name: 다음 문장 작성하기스
        run: |
          echo "달봉아~~"
          echo "사랑해! 지금도 많이 보고싶어!"